name: 🤖⏩ Synchronize develop
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  synchronize-dev:
    runs-on: ubuntu-latest
    steps:
      - name: 🤖⏩ Synchronize Develop Branch
        uses: knerd/sync-dev-action@v1
        with:
          # MAIN: main
          # DEVELOP: develop 
          BOT_NAME: 🤖 workflows[bot]2023
          BOT_EMAIL: devops+bot2023@muuvlabs.com
          TOKEN: ${{ secrets.GITHUB_TOKEN }}