name: 🤖⏩ Synchronize develop
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  synchronize-dev:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Checkout code 
        uses: actions/checkout@v3
        with:
          ref: main 

      - name: ⏩ Fast Forward develop
        id: merge
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "devops+bot2023@muuvlabs.com"
          git config --global user.name "🤖 workflows[bot]2023"
          git fetch --all
          git checkout develop
          if git merge --allow-unrelated-histories --ff-only main; then
            echo "Fast-forward merge successful"
            git push origin develop
          else
            echo "Fast-forward merge failed, creating a new branch and PR for manual review"
            branch_name="merge-main-to-develop-$(date +%Y%m%d%H%M%S)"
            git checkout -b $branch_name
            git merge --allow-unrelated-histories --no-edit -X theirs main
            git push -u origin $branch_name
            PR_URL=$(curl -s -X POST -H "Accept: application/vnd.github+json" -H "Authorization: token $TOKEN" "https://api.github.com/repos/${{ github.repository }}/pulls" -d "{ \"title\": \"🤖⏩ Merge main to develop\", \"head\": \"$branch_name\", \"base\": \"develop\" }" | jq -r ".html_url")
            echo "Created PR: $PR_URL"
          fi

      - name: 🌐 Get commit URL
        if: steps.merge.outcome == 'success'
        env:
          GITHUB_REPOSITORY_URL: https://github.com/${{ github.repository }}
        run: |
          commit_url=${GITHUB_REPOSITORY_URL}/commit/${{ github.event.after }}
          echo "::set-output name=commit_url::$commit_url"
